name: Feature Request
description: Template for requesting a feature
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request report!

        If what you're reporting is not a bug or issue with the plugin directly, please create a new discussion: https://github.com/AlexGustafsson/homebridge-wol/discussions.

        Example of issues that are not bugs or related to this plugin:

        * Wake command, start command or shutdown command do not work - this is user-supplied input and is executed by the plugin just like it would be executed if you were to type it in your own terminal

        Example of issues that are helpful to the project:

        * Feature suggestions - we love to hear what you envision for this project
        * Bug reports - is there a typo or badly handled edge case? We'd love to hear about it!
  - type: textarea
    attributes:
      label: General idea
      description: Please describe your suggested feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use case
      description: Please explain a use case for this feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Notes
      description: Please write about things that you did not see fit the above headers.
